### ISSUE TITLE
ignore_ids config not working for Mysql2

### ISSUE THREAD

**Issue by sbpipb** [harrystech/seed_migration#32] opened 2015-09-07 01:30 UTC
As stated in the wiki,

```
 ActiveRecord::Base.connection.reset_pk_sequence!
 which is pg only.

 If you need to use this gem with another database, use the ignore_ids configuration.
```

I followed this but still the error shows up.

```
 NoMethodError: undefined method `reset_pk_sequence!' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x007f9281b8bb20>
```

Here is my initializer file.

```
 SeedMigration.config do |c|
      c.ignore_ids = true
      c.extend_native_migration_task = true
 end
```

**Comment by pjambet** [comment] 2015-11-30 18:41
Hi,

Thanks for reporting this error, I'm going to take a look at this and update this issue with what I find.

(Sorry for the late reply)

**Comment by pjambet** [comment] 2015-11-30 22:13
I just tried in a new project, with seed_migration `1.0.7` and it worked fine.

Could you give me steps to reproduce this error?

Remember that `seeds.rb` is re written after running `rake seed:migrate`, so you'll need to re run the task to have a seeds file without `reset_pk_sequence!`

**Comment by hilary** [comment] 2015-12-10 02:19
@sbpipb `ignore_ids` is working fine for us with Mysql2, seed_migration `1.1.0`, Rails `4.1.5`, mysql2 `0.3.20`. Our initializer file looks just like yours.

**Comment by pjambet** [comment] 2017-08-01 09:09
Closing this for now as it seems to be fixed, feel free to reopen if you encouter the issue again.

**Closed by pjambet** 2017-08-01 09:09 UTC
Labels: bug
